package app

type CallbackQueryCommand uint

const (
	NotCallbackQueryCommand CallbackQueryCommand = iota
	SelectInitialLanguageCallbackQueryCommand
	SelectInitialPreferredCurrencyCallbackQueryCommand
	BalanceCallbackQueryCommand
	BuyNumberCallbackQueryCommand
	HelpCallbackQueryCommand
	HistoryCallbackQueryCommand
	LanguageCallbackQueryCommand
	MainMenuCallbackQueryCommand
	SelectSMSServiceCallbackQueryCommand
	PayServiceCallbackQueryCommand
	SelectLanguageCallbackQueryCommand
	CryptoBotListPayCurrenciesCallbackQueryCommand
	SelectTelegramStarsCallbackQueryCommand
	SelectCryptoBotPayCurrencyCallbackQueryCommand
	PreferredCurrenciesCallbackQueryCommand
	SelectPreferredCurrencyCallbackQueryCommand
	EmptyCallbackQueryCommand
	DeleteCryptoBotInvoiceCallbackQueryCommand
	ConfirmationPayServiceCallbackQueryCommand
	RefundAmountFromSMSActivationCallbackQueryCommand
	BackCallbackQueryCommand
	CancelEnterAmountCallbackQueryCommand
	CancelPayTelegramStarsCallbackQueryCommand
)
