package app

type CallbackQueryCommand uint

const (
	NotCallbackQueryCommand CallbackQueryCommand = iota
	BalanceCallbackQueryCommand
	BuyNumberCallbackQueryCommand
	HelpCallbackQueryCommand
	HistoryCallbackQueryCommand
	LanguageCallbackQueryCommand
	MainMenuCallbackQueryCommand
	SelectSMSServiceCallbackQueryCommand
	SelectSMSServiceWithCountryCallbackQueryCommand
	SelectLanguageCallbackQueryCommand
	ListPayCurrenciesCallbackQueryCommand
	SelectPayCurrencyCallbackQueryCommand
	PreferredCurrenciesCallbackQueryCommand
	SelectPreferredCurrencyCallbackQueryCommand
	EmptyCallbackQueryCommand
)
